### ISSUE TITLE
PyPI veripypi doesnt contain an sdist

### ISSUE THREAD

**Issue by jayvdb** [alichtman/veripypi#3]
Many python tools need an sdist, not a wheel, e.g. py2pack (and rach distro has their own tool like this), PyOxidizer.

Please upload an sdist, and ensure it includes a license.

Or/and create GitHub releases here.

Also tests to verify this tool works now and in the future.

**Comment by alichtman** [comment]
If you take a look at the source code for this project, you'll see that none of the functionality has been implemented. This is also why the project description begins with "WIP".

https://github.com/alichtman/veripypi/blob/ab178af0f66aa5f51241a0191a2d1f6d423e5844/veripypi/__main__.py#L38-L45

The PyPi package exists so that the name is claimed and if/when I get around to writing this tool, I will upload it. For now, it's just a concept.

> tests to verify this tool works now and in the future.

Hard to test code that hasn't been written yet.
